### ISSUE TITLE
Error when generate TFRecord with example code on Hadoop

### ISSUE THREAD

**Issue by mogumogu2333** [tensorflow/ecosystem#104]
Hi,

I'm trying to use MR to generate TFRecords. Currently I'm starting from the example code(TFRecordFileMRExample). But after package the jar and run a Hadoop application, I got the following errors.

I also locally test generating tfrecord by something like `java -cp tensorflow-hadoop-1.5.0.jar org.tensorflow.hadoop.example.TFRecordLocalExample` and it works. So I think the dependencies are successfully built. But hadoop job cannot build tfrecords.

My hadoop version is 2.7.1

Looking forward for any comments and solutions.

```
2018-10-11 05:28:54,606 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$Descriptor.getOneofs()Ljava/util/List;
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.<init>(GeneratedMessageV3.java:1727)
	at org.tensorflow.example.FeatureProtos.<clinit>(FeatureProtos.java:104)
	at org.tensorflow.example.Features$FeatureDefaultEntryHolder.<clinit>(Features.java:95)
	at org.tensorflow.example.Features$Builder.internalGetMutableFeature(Features.java:512)
	at org.tensorflow.example.Features$Builder.putFeature(Features.java:630)
	at org.tensorflow.hadoop.example.TFRecordFileMRExample$ToTFRecordMapper.map(TFRecordFileMRExample.java:61)
	at org.tensorflow.hadoop.example.TFRecordFileMRExample$ToTFRecordMapper.map(TFRecordFileMRExample.java:45)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1803)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
```

Thank you very much!

**Comment by skavulya** [comment]
I think the error is due to a mismatch between the protobuf-java version and the TensorFlow java version. You can figure out the protobuf-java version needed by looking at the compile dependencies in for TensorFlow proto. 

For example, if you want to compile the jar for TensorFlow 1.5.0, look at the protobuf dependencies for TensorFlow Proto 1.5.0 https://mvnrepository.com/artifact/org.tensorflow/proto/1.5.0 to determine that it depends on protobuf-java 3.3.1

Then compile as follows:
mvn versions:set -DnewVersion=1.5.0
mvn install -Dprotobuf.version=3.3.1

I hope this works for you.

**Comment by mogumogu2333** [comment]
Thanks @skavulya
