### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by charmby** [tensorflow/ecosystem#113]
Caused by: java.lang.NoSuchMethodError: org.tensorflow.example.BytesList$Builder.addValue(Lorg/tensorflow/spark/shaded/com/google/protobuf/ByteString;)Lorg/tensorflow/example/BytesList$Builder;
	at org.tensorflow.spark.datasources.tfrecords.serde.BytesListFeatureEncoder$$anonfun$encode$3.apply(FeatureEncoder.scala:68)
	at org.tensorflow.spark.datasources.tfrecords.serde.BytesListFeatureEncoder$$anonfun$encode$3.apply(FeatureEncoder.scala:67)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.tensorflow.spark.datasources.tfrecords.serde.BytesListFeatureEncoder$.encode(FeatureEncoder.scala:67)
	at org.tensorflow.spark.datasources.tfrecords.serde.DefaultTfRecordRowEncoder$.org$tensorflow$spark$datasources$tfrecords$serde$DefaultTfRecordRowEncoder$$encodeFeature(DefaultTfRecordRowEncoder.scala:118)
	at org.tensorflow.spark.datasources.tfrecords.serde.DefaultTfRecordRowEncoder$$anonfun$encodeExample$1.apply(DefaultTfRecordRowEncoder.scala:64)
	at org.tensorflow.spark.datasources.tfrecords.serde.DefaultTfRecordRowEncoder$$anonfun$encodeExample$1.apply(DefaultTfRecordRowEncoder.scala:61)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.tensorflow.spark.datasources.tfrecords.serde.DefaultTfRecordRowEncoder$.encodeExample(DefaultTfRecordRowEncoder.scala:61)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$2.apply(DefaultSource.scala:59)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$2.apply(DefaultSource.scala:56)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$.writePartitionLocal(DefaultSource.scala:179)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$.org$tensorflow$spark$datasources$tfrecords$DefaultSource$$mapFun$1(DefaultSource.scala:194)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$org$tensorflow$spark$datasources$tfrecords$DefaultSource$$writePartitionLocalFun$1.apply(DefaultSource.scala:196)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$org$tensorflow$spark$datasources$tfrecords$DefaultSource$$writePartitionLocalFun$1.apply(DefaultSource.scala:196)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chenzhaoyan** [comment]
Is this problem you resolved?
