### ISSUE TITLE
[hadoop] DataLossError after dump data to local disk

### ISSUE THREAD

**Issue by fromradio** [tensorflow/ecosystem#56]
Hi all, I am using the hadoop package and successfully transformed data to tfrecord on cluster. But after I dump the data to local disk and tried to use tensorflow to read the data using

```
for serialize_example in tf.python_io.tf_record_iterator(filename)
```

but I get the following error:

```
Traceback (most recent call last):
  File "tf_test.py", line 3, in <module>
    for serialize_example in tf.python_io.tf_record_iterator('tfrecord_test/test_file'):
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 77, in tf_record_iterator
    reader.GetNext(status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
```

Can anyone help on this problem?

**Comment by jhseu** [comment]
Considering it's at offset 0, the file is probably completely in the wrong format.

Please ask TF questions on StackOverflow so that others can find them.
