### ISSUE TITLE
[Hadoop] java.lang.NoClassDefFoundError: org/tensorflow/example/Int64List

### ISSUE THREAD

**Issue by FroilanYue** [tensorflow/ecosystem#75]
Hello,

I am trying to run the "src/main/java/org/tensorflow/hadoop/example/TFRecordFileMRExample.java" .

I am using Hadoop 2.9.0 and TensorFlow 1.6.0. After exec:
`mvn clean package`
I exec
`hadoop jar target/tensorflow-hadoop-1.6.0.jar org.tensorflow.hadoop.example.TFRecordFileMRExample /user/root`

And then it fails showing:

> java.lang.Exception: java.lang.NoClassDefFoundError: org/tensorflow/example/Int64List
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:491)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:551)
Caused by: java.lang.NoClassDefFoundError: org/tensorflow/example/Int64List
	at org.tensorflow.hadoop.example.TFRecordFileMRExample$ToTFRecordMapper.map(TFRecordFileMRExample.java:48)
	at org.tensorflow.hadoop.example.TFRecordFileMRExample$ToTFRecordMapper.map(TFRecordFileMRExample.java:43)

It seems something wrong with maven? I can find org.tensorflow.example, and this situation reappear despite I use another machine.

Any idea? Thanks

**Comment by FroilanYue** [comment]
Solved.
It's because the target/tensorflow-hadoop-1.6.0.jar don't contains the dependencies.
Should use an executable jar.
I failed using maven-assembly-plugin, but success with maven-shade-plugin.
And protobuf need relocation:

@pom.xml add
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-shade-plugin</artifactId>
  <version>3.1.0</version>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
        <goal>shade</goal>
      </goals>
      <configuration>
        <transformers>
          <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
            <mainClass>org.tensorflow.hadoop.example.TFRecordFileMRExample</mainClass>
          </transformer>
      </transformers>
      <relocations>
        <relocation>
          <pattern>com.google.protobuf</pattern>
          <shadedPattern>shaded.com.google.protobuf</shadedPattern>
        </relocation>
       </relocations>
      </configuration>
    </execution>
  </executions>
</plugin>
```
