### ISSUE TITLE
ClassNotFoundException: org.tensorflow.example.Features Error

### ISSUE THREAD

**Issue by pmehra7** [tensorflow/ecosystem#76]
I am following instructions here: https://docs.databricks.com/_static/notebooks/spark-tensorflow-connector.html 

Built the spark-tensorflow-connector and hadoop jars per instructions on the readme. The jars are passed in using the --jars spark shell argument. However, I am still getting the following error when executing: 

```df.repartition(1).write.format("tfrecords").option("recordType", "Example").mode("overwrite").save(path)```

**Comment by pmehra7** [comment]
```scala> df.repartition(1).write.format("tfrecords").option("recordType", "Example").mode("overwrite").save(path)
[Stage 0:=====================================================>   (28 + 2) / 30]WARN  2018-04-12 15:36:44,930 org.apache.spark.scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 30, 172.31.13.44, executor 0): org.apache.spark.SparkException: Task failed while writing rows
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$.org$apache$spark$internal$io$SparkHadoopMapReduceWriter$$executeTask(SparkHadoopMapReduceWriter.scala:178)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:89)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:88)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/tensorflow/example/Features
	at org.tensorflow.spark.datasources.tfrecords.serde.DefaultTfRecordRowEncoder$.encodeExample(DefaultTfRecordRowEncoder.scala:58)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$2.apply(DefaultSource.scala:59)
	at org.tensorflow.spark.datasources.tfrecords.DefaultSource$$anonfun$2.apply(DefaultSource.scala:56)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:147)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:144)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
	at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$.org$apache$spark$internal$io$SparkHadoopMapReduceWriter$$executeTask(SparkHadoopMapReduceWriter.scala:159)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.tensorflow.example.Features
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more```

**Comment by pmehra7** [comment]
I have attached the following jars: 
1. original-spark-tensorflow-connector_2.11-1.6.0.jar
2. tensorflow-hadoop-1.6.0.jar
3. tensorflow-1.6.0.jar
4. libtensorflow-1.6.0.jar

**Comment by pmehra7** [comment]
Used the wrong spark-tensorflow-connector jar
