### ISSUE TITLE
[spark-tensorflow-connector] failed to load tfrecord files using tensorflow

### ISSUE THREAD

**Issue by Seanspt** [tensorflow/ecosystem#84]
I'm trying out spark-tensorflow-connector on my mac book
with 
>tensorflow version 1.8.0
>hadoop version 2.6.5
>spark version 2.1.1

run spark in local mode with the following code:
```python
from pyspark.sql import Row
from pyspark.sql.types import StructType
from pyspark.sql.types import StructField
from pyspark.sql.types import *


rows = [Row(11, 1, 23, 10.9, 14.0, [1.0, 2.0], 'r1'), 
Row(21, 2, 24, 12.0, 15.0, [2.0,2.0],'r2')]

schema = StructType([StructField("id", IntegerType()),
StructField("IntegerTypeLabel", IntegerType()),
StructField("LongTypeLabel", LongType()),
StructField("FloatTypeLabel", FloatType()),
StructField("DoubleTypeLabel", DoubleType()),
StructField("VectorLabel", ArrayType(DoubleType(), True)),
StructField("name", StringType())])

df = spark.createDataFrame(rows, schema)
df.write.mode("overwrite").format("tfrecords").option("recordType", "Example").save("./test")
```

when trying to load it in tensorflow as followed:
```python
import tensorflow as tf
dataset = tf.data.TFRecordDataset(['part-r-00003'])


def decode(x):
    feature = {'id': tf.int32,
               'IntegerTypeLabel': tf.int32,
               'LongTypeLable': tf.int64,
               'FloatTypeLabel': tf.float32,
               'DoubleTypeLabel': tf.float64,
               'VectorLabel': tf.FixedLenFeature([],tf.float64),
               'name': tf.string}
    return tf.parse_single_example(x,features=feature)

dataset = dataset.map(decode)
dataset = dataset.batch(1)
iterator = dataset.make_one_shot_iterator()
next = iterator.get_next()
with tf.Session() as sess:
    print(sess.run(next))
```
An error is raised:
```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1804, in tf_map_func
    ret = map_func(nested_args)
  File "<stdin>", line 9, in decode
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/parsing_ops.py", line 758, in parse_single_example
    return parse_single_example_v2(serialized, features, name)
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/parsing_ops.py", line 1279, in parse_single_example_v2
    [VarLenFeature, SparseFeature, FixedLenFeature, FixedLenSequenceFeature])
  File "/Users/sean/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/parsing_ops.py", line 296, in _features_to_raw_params
    raise ValueError("Invalid feature %s:%s." % (key, feature))
ValueError: Invalid feature DoubleTypeLabel:<dtype: 'float64'>.
```
one of the files spark generated is:
```python
b'\n\xa6\x01\n\x0b\n\x02id\x12\x05\x1a\x03\n\x01\x0b\n\x19\n\x10IntegerTypeLabel\x12\x05\x1a\x03\n\x01\x01\n\x16\n\rLongTypeLabel\x12\x05\x1a\x03\n\x01\x17\n\x1a\n\x0eFloatTypeLabel\x12\x08\x12\x06\n\x04ff.A\n\x1b\n\x0fDoubleTypeLabel\x12\x08\x12\x06\n\x04\x00\x00`A\n\x1b\n\x0bVectorLabel\x12\x0c\x12\n\n\x08\x00\x00\x80?\x00\x00\x00@\n\x0e\n\x04name\x12\x06\n\x04\n\x02r1'
```

I'm trying to figure out why. Could any body give me hint?

**Comment by manuzhang** [comment]
Note the allowed data types are `VarLenFeature, SparseFeature, FixedLenFeature, FixedLenSequenceFeature` so try defining a feature like `'id': tf.FixedLenFeature([], tf.int32)`.

Another thing is the `DoubleTypeLabel` you write out may be of type `tf.FixedLenFeature([], tf.float32)`

**Comment by Seanspt** [comment]
thanks a lot, @manuzhang . The following decode function works.
```python
def decode(x):
    feature = {'id': tf.FixedLenFeature([], tf.int64),
               'IntegerTypeLabel': tf.FixedLenFeature([], tf.int64),
               'LongTypeLabel': tf.FixedLenFeature([],tf.int64),
               'FloatTypeLabel': tf.FixedLenFeature([], tf.float32),
               'DoubleTypeLabel': tf.FixedLenFeature([],tf.float32),
               'VectorLabel': tf.VarLenFeature(tf.float32),}
    return tf.parse_single_example(x,features=feature)
```
