### ISSUE TITLE
[spark-tensorflow-connector] Reading TFRecord throws NoSuchElementException

### ISSUE THREAD

**Issue by manuzhang** [tensorflow/ecosystem#86]
The following exception is thrown when I read tfrecord with  

```scala
spark.read.format("tfrecords").load(path)
```

```
java.util.NoSuchElementException: key not found: path
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.default(CaseInsensitiveMap.scala:28)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.apply(CaseInsensitiveMap.scala:28)
	at org.tensorflow.spark.datasources.tfrecords.TensorflowRelation.x$1$lzycompute(TensorflowRelation.scala:33)
	at org.tensorflow.spark.datasources.tfrecords.TensorflowRelation.x$1(TensorflowRelation.scala:32)
	at org.tensorflow.spark.datasources.tfrecords.TensorflowRelation.tfSchema$lzycompute(TensorflowRelation.scala:32)
	at org.tensorflow.spark.datasources.tfrecords.TensorflowRelation.tfSchema(TensorflowRelation.scala:32)
	at org.tensorflow.spark.datasources.tfrecords.TensorflowRelation.schema(TensorflowRelation.scala:59)
	at org.apache.spark.sql.execution.datasources.LogicalRelation$.apply(LogicalRelation.scala:77)
	at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:423)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
```

Instead, `path` has to be set in `option` like

```scala
spark.read.format("tfrecords").option("path", path).load()
```

Maybe the README needs update ?

**Comment by skavulya** [comment]
@manuzhang I tried the README example and it works fine.  Had you set the path variable? What version of Spark are you using?

**Comment by manuzhang** [comment]
@skavulya Did you read with `spark.read.format("tfrecords").load(path)` ?

**Comment by skavulya** [comment]
@manuzhang Yes. I am wondering if the issue might be due to differences in Spark versions because `spark.read.format("tfrecords").load(path)` works on my system.

**Comment by manuzhang** [comment]
@skavulya It was my mistake that I was doing `spark.read.format("tfrecords").load(paths: _*)`. Thanks for your time.

**Comment by skavulya** [comment]
@manuzhang No problem. Thanks!
